# Generated by Django 5.0.4 on 2024-04-16 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(default=False, upload_to='productos')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('categoria', models.CharField(choices=[('Electronicos', 'Electronicos'), ('Notebooks', 'Notebooks'), ('Celulares', 'Celulares'), ('Consolas', 'Consolas'), ('Tablets', 'Tablets'), ('Otros', 'Otros')], max_length=20)),
            ],
        ),
    ]
