# Generated by Django 5.0.4 on 2024-04-20 23:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('precio', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('stock', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('categoria', models.CharField(choices=[('Electronicos', 'Electronicos'), ('Notebooks', 'Notebooks'), ('Celulares', 'Celulares'), ('Consolas', 'Consolas'), ('Tablets', 'Tablets'), ('Otros', 'Otros')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('subtotal', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_compra', models.DateTimeField(auto_now_add=True)),
                ('total', models.PositiveIntegerField()),
                ('direccion', models.CharField(max_length=30)),
                ('recibe', models.CharField(max_length=40)),
                ('comuna', models.CharField(choices=[('Santiago', 'Santiago'), ('Maipú', 'Maipú'), ('Providencia', 'Providencia'), ('Las Condes', 'Las Condes'), ('Ñuñoa', 'Ñuñoa'), ('La Florida', 'La Florida'), ('La Cisterna', 'La Cisterna'), ('Puente Alto', 'Puente Alto'), ('San Bernardo', 'San Bernardo')], max_length=20)),
                ('compra', models.ManyToManyField(to='productos.carrito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
