# Generated by Django 5.0.4 on 2024-04-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('Enviado', 'Enviado'), ('Recibido', 'Recibido'), ('En bodega', 'En bodega')], default='En bodega', max_length=20),
        ),
    ]
