# Generated by Django 5.0.4 on 2024-04-21 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_compraproducto_alter_ordencompra_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compraproducto',
            name='producto',
        ),
        migrations.AddField(
            model_name='compraproducto',
            name='cant_prod',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='compraproducto',
            name='nom_prod',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='compraproducto',
            name='sub_prod',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
