# Generated by Django 5.0.4 on 2024-04-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_producto_imagen_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
