# Generated by Django 5.0.4 on 2024-04-21 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_remove_ordencompra_compra_ordencompra_compra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compraproducto',
            old_name='nom_prod',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='compraproducto',
            name='cant_prod',
        ),
        migrations.RemoveField(
            model_name='compraproducto',
            name='sub_prod',
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='compra',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='productos.compraproducto'),
        ),
    ]
